name: Sync labels

on:
    schedule:
        - cron: "0 3 * * 0"
    push:
        branches: [main]
        paths: [.github/workflows/sync-labels.yml]
    workflow_dispatch:

jobs:
    run:
        uses: Friedinger/Configs/.github/workflows/action-sync-labels.yml@5be661d1643193dea627bb33ea8d8f9de6e10b42 # main
        permissions:
            issues: write
